##########################################################################################################
################################# Chapter 1: Setting the Stage | Page 61 #################################
##########################################################################################################


####### Exercise 1 ########



```{r}
#install.packages("freqparcoord")
require(freqparcoord)
data(mlb)
```

```{r}
### Checking for linear model

xvalpart <- function(data, p)
{
  n <- nrow(data)
  ntrain <- round(p*n)
  trainidxs <- sample(1:n, ntrain, replace = FALSE)
  list(train = data[trainidxs,], valid = data[-trainidxs,])
}
```

```{r}
xvallm <- function(data, ycol, predvars, p, meanabs = TRUE)
{
  tmp <- xvalpart(data, p)
  train <- tmp$train
  valid <- tmp$valid
  #fit model to training data
  trainy <- train[,ycol]
  trainpreds <- train[,predvars]
  # using matrix form in lm() call
  trainpreds <- as.matrix(trainpreds)
  lmout <- lm(trainy ~ trainpreds)
  # apply fitted model to validation data; not that %*% works only on matrices, not data frames
  validpreds <- as.matrix(valid[,predvars])
  predy <- cbind(1, validpreds)%*%coef(lmout)
  realy <- valid[,ycol]
  if(meanabs)
    return (mean(abs(predy - realy)))
  list(predy = predy, realy = realy)
}

```

```{r}
#Check with 80-20 split

xvallm(mlb,5 ,c(4 ,6) ,2/3) #13.87
xvallm(mlb,5 ,c(4 ,6) ,1/3) #13.03
xvallm(mlb,5 ,c(4 ,6) ,1/2) #14.16
xvallm(mlb,5 ,c(4 ,6) ,4/5) #12.73

# As expected the results of cross validation are random with different split.
```

```{r}
### Checking the same for KNN algorithm 

xvalknn <- function(data, ycol, predvars, k, p, meanabs = TRUE)
{
  data <- data[,c(predvars, ycol)]
  ycol <- length(predvars) + 1
  tmp <- xvalpart(data, p)
  train <- tmp$train
  valid <- tmp$valid
  valid <- as.matrix(valid)
  xd <- preprocessx(train[,-ycol], TRUE)
  kout <- knnest(train[,ycol], xd, k)
  predy <- predict(kout, valid[,-ycol], TRUE)
  realy <- valid[,ycol]
  if(meanabs)
    return (mean(abs(predy - realy)))
  list(predy = predy, realy = realy)
}
```

```{r}
#install.packages("regtools")
require(regtools)
set.seed(9999)
kvalknn(mlb, 5, c(4,6), 25, 2/3)
```

```{r}
####### Exercise 2 ########


library(freqparcoord)
data(prgeng)
prgeng$age2 <- prgeng$age^2
edu <- prgeng$educ
prgeng$ms <- as.integer(edu == 14)
prgeng$phd <- as.integer(edu == 16)
prgeng$fem <- prgeng$sex - 1
tmp <- prgeng[edu >= 13,]
pe <- tmp[ ,c(1 ,12 ,9 ,13 ,14 ,15 ,8)]
pe <- as.matrix(pe)

```

```{r}
#Default model
lm(wageinc ~ age + age2 + wkswrkd + ms + phd + fem, data = prgeng )
```

```{r}
#Refined model after including interaction terms between age & gender and age^2 & gender

prgeng$agefem <- prgeng$age * prgeng$fem
prgeng$age2fem <- prgeng$age2 * prgeng$fem

lm(wageinc ~ age + age2 + wkswrkd + ms + phd + fem + agefem + age2fem, data = prgeng )

# second way as suggested in book
# lm(wageinc ~ age + age2 + wkswrkd + ms + phd + fem + age:fem + age2:fem, data = prgeng )
```

```{r}
####### Exercise 3 ########

#install.packages("mfp")
require(mfp)
data(bodyfat)
df <- bodyfat[,4:17]
```

```{r}
model <- lm(density ~ age + weight + height + neck + chest + abdomen + hip + thigh + knee + ankle + biceps + 
     forearm + wrist, data = bodyfat)

summary(model)
```

```{r}
plot(model)
```

```{r}
# As can be observed from the plot, the residuals are not normally distributed. 
# This model does not seem to explain the variation in density effectively and needs to be refined 
# in order to improve the accuracy
```

```{r}
####### Exercise 4 ########

# (i) Mean height of people is the weighted average of each gender, 
#     with weight for each gender being its proportion of the total population

# (i) Mean proportion of people taller than 70 inches is the weighted average of each gender, 
#     with weight for each gender being its proportion of the total population taller than 70 inches
```

```{r}
##########################################################################################################
############################# Chapter 2: Linear Regression Models | Page 120 #############################
##########################################################################################################

####### Exercise 1 ########

library(freqparcoord)
data(prgeng)
prgeng$age2 <- prgeng$age^2
edu <- prgeng$educ
prgeng$ms <- as.integer(edu == 14)
prgeng$phd <- as.integer(edu == 16)
prgeng$fem <- prgeng$sex - 1
tmp <- prgeng[edu >= 13,]
pe <- tmp[ ,c(1 ,12 ,9 ,13 ,14 ,15 ,8)]
pe <- as.matrix(pe)
```

```{r}
#Default model
model <- lm(wageinc ~ age + age2 + wkswrkd + ms + phd + fem, data = prgeng )

summary(model)

# From the summary, we get R squared value is 0.2356 and adj. R squared value is 0.2354

```

```{r}
# 95% CI for b6 (fem)

lcl <- -11484.49 - 1.96*705.3
ucl <- -11484.49 + 1.96*705.3

lcl
ucl
```

```{r}
# 95% CI for b7 (msfem)

#Refined model

prgeng$msfem <- prgeng$ms * prgeng$fem
prgeng$phdfem <- prgeng$phd * prgeng$fem
model <- lm(wageinc ~ age + age2 + wkswrkd + ms + phd + fem + msfem + phdfem, data = prgeng )

summary(model)
```

```{r}
lcl <- -10276.797 - 1.96*804.498 -4157.253 - 1.96*1728.329
ucl <- -10276.797 + 1.96*804.498 -4157.253 + 1.96*1728.329

lcl
ucl
```

```{r}
####### Exercise 2 ########

df <- read.csv("day.csv", sep = ",")
df$temp2 <- df$temp^2
model <- lm(registered ~ temp + temp2 + season + workingday + windspeed + yr, data = df)
summary(model)

```

```{r}
# This dataset has yr variable having 0 value for year 1 and 1 value for year 2. Based on this 95% CI is

lcl <- 1757.75 - 1.96*53.97
ucl <- 1757.75 + 1.96*53.97

lcl
ucl
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).
